name: flutter_quizzy

description: A Flutter port of Quiz Me Smart with Supabase auth and OpenTDB quizzes.

publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.6.0
  http: ^1.2.2
  provider: ^6.1.2
  go_router: ^14.2.7
  flutter_dotenv: ^5.1.0
  html_character_entities: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
